### ISSUE TITLE
Ability to interact with User Scripts plugin

### ISSUE THREAD

**Issue by stomko11** [domalab/ha-unraid#11]
**Is your feature request related to a problem? Please describe.**
Although user scripts are supported, few of us use "User Script" as a plugin on Unraid that allows creating scripts via GUI. This, however, does not create typical .sh file, instead path containing 3 files (name, description, schedule). Would be nice if your integration could handle that

**Describe the solution you'd like**
Be able to run scripts that are not ".sh". It would be actually cool to list scripts found in path as entites, so you could run them directly from gui

**Additional context**
None

**Comment by domalab** [comment]
@stomko11 Thank you very much for submitting the enhancement request.

I'll add it to my list to get implemented. 😊

**Comment by domalab** [comment]
@stomko11 I had a think about this request and I'm going to create a new entity platform for user scripts that will represent each script as a button entity.

It will look for scripts here

 "/boot/config/plugins/user.scripts/scripts",
 "/usr/local/emhttp/plugins/user.scripts/scripts"

Can be used in automations like so

```
# Example automation to run a script
automation:
  trigger:
    platform: time
    at: "03:00:00"
  action:
    service: button.press
    target:
      entity_id: button.run_backup_script

# Example automation with error handling
automation:
  trigger:
    platform: event
    event_type: script_error
  action:
    service: notify.notify
    data:
      message: "Script failed: {{ trigger.event.data.error }}"
```
