### ISSUE TITLE
Add new services to perform basic controls. Stop the array, rebooting, or shutting down the system.

### ISSUE THREAD

**Issue by domalab** [domalab/ha-unraid#6]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to control basic Unraid system functions through Home Assistant. Users need to manually access the Unraid dashboard or use SSH to perform operations like stopping the array, rebooting, or shutting down the system. This makes it difficult to automate these operations or integrate them into Home Assistant automations/scripts.

**Describe the solution you'd like**
Add three new services to perform basic system control:

1. `unraid.array_stop` - To safely stop the array
2. `unraid.system_reboot` - To reboot the server
3. `unraid.system_shutdown` - To shutdown the server

Each service should include:
- Safety checks (VMs running, active operations, etc.)
- Optional delay parameter for scheduled operations
- Status reporting for success/failure
- Clear error messages

**Additional context**
Example usage in automation:
```yaml
automation:
  - alias: "Scheduled Maintenance"
    trigger:
      - platform: time
        at: "03:00:00"
    action:
      - service: unraid.array_stop
        data:
          entry_id: YOUR_ENTRY_ID
      - delay: "00:02:00"
      - service: unraid.system_reboot
        data:
          entry_id: YOUR_ENTRY_ID
          delay: 300  # 5 minute warning
```

These services would enable proper automation of system maintenance and emergency procedures through Home Assistant, rather than requiring manual intervention through the Unraid dashboard or SSH.
