### ISSUE TITLE
Enhancement: Sensors for disks temperature and spinning status

### ISSUE THREAD

**Issue by tomaszkoc** [domalab/ha-unraid#82]
### **Describe the Solution You'd Like**

I would like to monitor the temperature and spinning state of all disks in the array, have a history of drives' temperatures and statuses in HA database for further analysis.

---

### **Use Case or Why Do You Want This?**

Identifying the times of heavy usage in the middle of the night - possibly find scheduled tasks that might be overheating the drives.
Checking if the drives ever spin down / spin down correctly according to set timers.
Verifying if the the Unraid script that controls the fans depending on the disk's temperatures works properly (the sensors for fans are already available).

---

### **Additional Details or Considerations**

The integration could also include buttons/actions for spinning individual drives up or down, to use in HA automations (example spin down Unraid drives when logging of systems / leaving home, spin up drives when "home theater" scene enabled etc.)

**Comment by ruaan-deysel** [comment]
Hi @tomaszkoc! 👋

Thank you for this enhancement request. After reviewing your requirements and analysing the current integration, I have some great news: **most of the functionality you're looking for is already available!** 🎉

## ✅ Already Available Features

The integration already provides comprehensive disk monitoring through sensor attributes:

### 🌡️ **Disk Temperature Monitoring**
- **Available in**: All disk usage sensors (e.g., `sensor.cube_disk1_usage`, `sensor.cube_cache_usage`)
- **Attribute**: `temperature` 
- **Behavior**: 
  - Shows actual temperature when disk is active (e.g., "42°C")
  - Shows "N/A (Standby)" when disk is spun down (preserves last known temperature)
  - Automatically handles both SATA and NVMe drives

### ⚡ **Disk Spinning Status**
- **Available in**: All disk usage sensors and disk health binary sensors
- **Attributes**: 
  - `power_state`: "active" or "standby"
  - `disk_status`: "Active" or "Standby (Spun Down)"
- **Real-time monitoring**: Updates every few minutes based on your configured intervals

### 📊 **Additional Disk Data Already Available**
- **Health Status**: Available in disk health binary sensors (`binary_sensor.cube_disk1_health`)
- **SMART Status**: Available as attributes when disk is active
- **Spin Down Settings**: `spin_down_delay` attribute shows configured timeout
- **Device Information**: Device path, serial number, filesystem type
- **Storage Metrics**: Capacity, usage, available space

## 🏠 **How to Use This Data in Home Assistant**

### **1. Create Temperature History Dashboard**
```yaml
type: history-graph
entities:
  - entity: sensor.cube_disk1_usage
    attribute: temperature
    name: "Disk 1 Temperature"
  - entity: sensor.cube_disk2_usage
    attribute: temperature
    name: "Disk 2 Temperature"
hours_to_show: 24
refresh_interval: 0
```

### **2. Monitor Disk Spinning Status**
```yaml
type: entities
entities:
  - entity: sensor.cube_disk1_usage
    secondary_info: attribute
    attribute: power_state
    name: "Disk 1 Power State"
  - entity: sensor.cube_disk2_usage
    secondary_info: attribute
    attribute: power_state
    name: "Disk 2 Power State"
```

### **3. Automation Examples**

**Detect Heavy Usage at Night:**
```yaml
alias: "Detect Nighttime Disk Activity"
trigger:
  - platform: state
    entity_id: sensor.cube_disk1_usage
    attribute: power_state
    to: "active"
  - platform: state
    entity_id: sensor.cube_disk2_usage
    attribute: power_state
    to: "active"
condition:
  - condition: time
    after: "22:00:00"
    before: "06:00:00"
action:
  - service: notify.mobile_app_your_phone
    data:
      message: "Disk {{ trigger.entity_id.split('.')[1] }} became active at night - possible scheduled task"
```

**Monitor Disk Temperatures:**
```yaml
alias: "High Disk Temperature Alert"
trigger:
  - platform: template
    value_template: >
      {% set temp = state_attr('sensor.cube_disk1_usage', 'temperature') %}
      {{ temp != 'N/A (Standby)' and temp != 'N/A' and temp|int > 50 }}
action:
  - service: notify.mobile_app_your_phone
    data:
      message: "Disk 1 temperature is high: {{ state_attr('sensor.cube_disk1_usage', 'temperature') }}"
```

**Verify Spin Down Behavior:**
```yaml
alias: "Track Disk Spin Down Events"
trigger:
  - platform: state
    entity_id: sensor.cube_disk1_usage
    attribute: power_state
    to: "standby"
action:
  - service: logbook.log
    data:
      name: "Disk Management"
      message: "Disk 1 spun down at {{ now().strftime('%H:%M:%S') }} (configured delay: {{ state_attr('sensor.cube_disk1_usage', 'spin_down_delay') }})"
```

## 📈 **Template Sensors for Enhanced Monitoring**

You can create dedicated temperature sensors for easier graphing:

```yaml
template:
  - sensor:
      - name: "Disk 1 Temperature"
        unit_of_measurement: "°C"
        device_class: temperature
        state: >
          {% set temp = state_attr('sensor.cube_disk1_usage', 'temperature') %}
          {% if temp not in ['N/A (Standby)', 'N/A', 'unknown'] %}
            {{ temp.replace('°C', '') | int }}
          {% else %}
            {{ states('sensor.disk1_temperature') | default('unknown') }}
          {% endif %}
        availability: >
          {{ state_attr('sensor.cube_disk1_usage', 'temperature') not in ['N/A', 'unknown'] }}
```

## 🔧 **Regarding Spin Up/Down Controls**

For the disk spin up/down control buttons you mentioned, this would require additional implementation as it involves potentially disruptive disk operations. However, you can achieve similar results using:

1. **Unraid's built-in spin down timers** (already monitored via `spin_down_delay` attribute)
2. **User scripts** executed via the existing `unraid.execute_user_script` service
3. **SSH commands** via the existing `unraid.execute_command` service (use with caution)

## 🎯 **Conclusion**

The integration already provides comprehensive disk temperature and spinning status monitoring through sensor attributes. You can:

✅ **Monitor disk temperatures** with full history
✅ **Track spinning status** in real-time
✅ **Detect nighttime activity** with automations
✅ **Verify spin down behavior** with state tracking
✅ **Monitor disk health** with dedicated binary sensors

No code changes are needed - everything is already available as sensor attributes! The examples above should help you achieve all your monitoring goals.
